### ISSUE TITLE
OBconf says your openbox theme is not a valid openbox theme directory

### ISSUE THREAD

**Issue by mrnatbus12** [onodera-punpun/dotfiles#4]
This error occurs when attempting to create a .obt file for your theme

**Comment by onodera-punpun** [comment]
I don't use OBconf. Anyways I symlink all my dotfiles (check https://github.com/onodera-punpun/dotfiles/blob/master/symlink)

you should move ln ``openbox/theme`` to  ``$HOME/.themes/minato/openbox-3``
