### ISSUE TITLE
Do you have a list of wallpapers that you use in your rices?

### ISSUE THREAD

**Issue by lewis-carson** [onodera-punpun/dotfiles#6]
They all look beautiful and I was wondering if you have a source of some sort.

**Comment by CamilleScholtz** [comment]
I mostly get them from Japanese Flickr accounts, lol.

A good starting point would be https://www.flickr.com/photos/gooldays and https://www.flickr.com/photos/so87/, if you go into the Favorites rabbit hole you'll find many more acocunts like these.

**Comment by lewis-carson** [comment]
Thanks, you were a great help

**Comment by CamilleScholtz** [comment]
np :)
